import { useEffect, useState } from "react";
import api from "../lib/api";

function makeQuestion(index) {
  return {
    prompt: "",
    max_marks: 10,
    type: "text",
    options: []
  };
}

function QuestionBuilder({ room, onBack, onSaved }) {
  const safeRoomId = room?.room_id || "";
  const [title, setTitle] = useState(room?.course_title || room?.title || "Exam Paper");
  const [durationMinutes, setDurationMinutes] = useState(30);
  const [questions, setQuestions] = useState([makeQuestion(0)]);
  const [loading, setLoading] = useState(false);
  const [message, setMessage] = useState("");
  const [error, setError] = useState("");

  const extractErrorMessage = (requestError, fallback) => {
    const detail = requestError?.response?.data?.detail;
    if (Array.isArray(detail) && detail.length > 0) {
      const first = detail[0];
      if (typeof first === "string") {
        return first;
      }
      if (first?.msg) {
        return first.msg;
      }
      return fallback;
    }
    if (typeof detail === "string") {
      return detail;
    }
    if (typeof requestError?.message === "string" && requestError.message.trim()) {
      return requestError.message;
    }
    return fallback;
  };

  const loadPaper = async () => {
    if (!safeRoomId) {
      setError("Invalid room context. Please go back and reopen paper editor.");
      return;
    }
    setLoading(true);
    setError("");
    try {
      const response = await api.get(`/rooms/${safeRoomId}/paper`);
      const paper = response.data;
      setTitle(paper.title);
      setDurationMinutes(paper.duration_minutes);
      const mappedQuestions = (paper.questions || []).map((item, index) => ({
          prompt: item.prompt || "",
          max_marks: Number(item.max_marks ?? 10) || 10,
          type: item.type === "mcq" ? "mcq" : "text",
          options: Array.isArray(item.options) ? item.options : []
        }));

      if (room?.strip_autogenerated_questions && mappedQuestions.length === 1) {
        const first = mappedQuestions[0];
        const promptLooksGenerated = /^Question\s+1$/i.test((first.prompt || "").trim());
        const marksLooksDefault = Number(first.max_marks || 10) === 10;
        const isTextWithoutOptions = first.type === "text" && (!first.options || first.options.length === 0);
        if (promptLooksGenerated && marksLooksDefault && isTextWithoutOptions) {
          setQuestions([]);
        } else {
          setQuestions(mappedQuestions);
        }
      } else {
        setQuestions(mappedQuestions);
      }
    } catch (requestError) {
      setError(extractErrorMessage(requestError, "Could not load question paper"));
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    loadPaper();
  }, [safeRoomId]);

  const updateQuestion = (index, key, value) => {
    setQuestions((current) =>
      current.map((item, idx) => {
        if (idx !== index) {
          return item;
        }
        if (key === "type") {
          return {
            ...item,
            type: value,
            options: value === "mcq" ? item.options.length ? item.options : ["", ""] : []
          };
        }
        if (key === "max_marks") {
          return {
            ...item,
            max_marks: value
          };
        }
        return { ...item, [key]: value };
      })
    );
  };

  const addQuestion = () => {
    setQuestions((current) => [...current, makeQuestion(current.length)]);
  };

  const removeQuestion = (index) => {
    setQuestions((current) => current.filter((_, idx) => idx !== index));
  };

  const updateOption = (qIndex, oIndex, value) => {
    setQuestions((current) =>
      current.map((item, idx) => {
        if (idx !== qIndex) {
          return item;
        }
        const nextOptions = [...item.options];
        nextOptions[oIndex] = value;
        return { ...item, options: nextOptions };
      })
    );
  };

  const addOption = (qIndex) => {
    setQuestions((current) =>
      current.map((item, idx) => {
        if (idx !== qIndex) {
          return item;
        }
        return { ...item, options: [...item.options, ""] };
      })
    );
  };

  const removeOption = (qIndex, oIndex) => {
    setQuestions((current) =>
      current.map((item, idx) => {
        if (idx !== qIndex) {
          return item;
        }
        return { ...item, options: item.options.filter((_, currentOptionIdx) => currentOptionIdx !== oIndex) };
      })
    );
  };

  const savePaper = async () => {
    if (questions.length === 0) {
      setError("Add at least one question before saving the paper");
      return;
    }

    const hasEmptyPrompt = questions.some((item) => !item.prompt?.trim());
    if (hasEmptyPrompt) {
      setError("Each question must have a prompt before saving");
      return;
    }

    const hasInvalidMaxMarks = questions.some((item) => {
      const marks = Number(item.max_marks);
      return !Number.isFinite(marks) || marks <= 0;
    });
    if (hasInvalidMaxMarks) {
      setError("Each question must have max marks greater than 0");
      return;
    }

    setLoading(true);
    setError("");
    setMessage("");
    try {
      const payloadQuestions = questions.map((item, index) => ({
        id: `q${index + 1}`,
        prompt: item.prompt,
        max_marks: Number(item.max_marks || 0),
        type: item.type,
        options: item.type === "mcq" ? item.options.filter((value) => value.trim()) : []
      }));

      const response = await api.put(`/rooms/${safeRoomId}/paper`, {
        title,
        duration_minutes: durationMinutes,
        questions: payloadQuestions
      });
      setMessage("Question paper saved");
      if (onSaved) {
        onSaved({ exam_id: response.data.id, title: response.data.title });
      }
    } catch (requestError) {
      setError(extractErrorMessage(requestError, "Could not save question paper"));
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="panel question-builder-panel">
      <h2>Question Paper Builder</h2>
      <p className="muted">Room {safeRoomId || "N/A"} - Build questions like a form editor and publish instantly.</p>

      <div className="inline-row builder-meta-row">
        <label>
          Exam Title
          <input value={title} onChange={(event) => setTitle(event.target.value)} required />
        </label>
        <label>
          Duration (min)
          <input
            type="number"
            min="1"
            max="300"
            value={durationMinutes}
            onChange={(event) => setDurationMinutes(Number(event.target.value))}
          />
        </label>
      </div>

      <div className="builder-list">
        {questions.map((question, index) => (
          <div key={`question-${index}`} className="builder-card">
            <div className="inline-row builder-question-header">
              <strong>Question {index + 1}</strong>
              <label className="builder-mark-input">
                Max Marks
                <input
                  type="number"
                  min="0.1"
                  step="0.5"
                  value={question.max_marks ?? 10}
                  onChange={(event) => updateQuestion(index, "max_marks", event.target.value)}
                  required
                />
              </label>
              <button className="danger-btn" onClick={() => removeQuestion(index)} type="button">
                Remove
              </button>
            </div>
            <label>
              Prompt
              <textarea
                rows={3}
                value={question.prompt}
                onChange={(event) => updateQuestion(index, "prompt", event.target.value)}
                required
              />
            </label>
            <label>
              Type
              <select value={question.type} onChange={(event) => updateQuestion(index, "type", event.target.value)}>
                <option value="text">Text Answer</option>
                <option value="mcq">Multiple Choice</option>
              </select>
            </label>

            {question.type === "mcq" ? (
              <div className="builder-options">
                <strong>Options</strong>
                {question.options.map((option, optionIndex) => (
                  <div key={`q-${index}-opt-${optionIndex}`} className="inline-row">
                    <input
                      value={option}
                      onChange={(event) => updateOption(index, optionIndex, event.target.value)}
                      placeholder={`Option ${optionIndex + 1}`}
                      required
                    />
                    <button
                      className="danger-btn"
                      type="button"
                      onClick={() => removeOption(index, optionIndex)}
                    >
                      Remove Option
                    </button>
                  </div>
                ))}
                <button type="button" onClick={() => addOption(index)}>
                  Add Option
                </button>
              </div>
            ) : null}
          </div>
        ))}
      </div>

      <div className="row-actions">
        <button type="button" onClick={addQuestion}>
          Add Question
        </button>
        <button type="button" onClick={savePaper} disabled={loading}>
          Save Paper
        </button>
        <button type="button" className="linkish" onClick={onBack}>
          Back To Teacher Dashboard
        </button>
      </div>

      {message ? <p className="muted">{message}</p> : null}
      {error ? <p className="error">{error}</p> : null}
    </div>
  );
}

export default QuestionBuilder;
